apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwd      
  hostPath:
    path: "/data/mysql"
  persistentVolumeReclaimPolicy: Retain
